"""restore_campaigns_without_projects

Revision ID: 4945a0a21a74
Revises: q1r2s3t4u5
Create Date: 2026-05-10 00:17:08.517050
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4945a0a21a74'
down_revision: Union[str, None] = 'q1r2s3t4u5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_campaigns_project_id', table_name='campaigns')
    op.drop_constraint('uq_campaign_project_name', 'campaigns', type_='unique')
    op.drop_constraint('campaigns_project_id_fkey', 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'project_id')
    op.drop_index('idx_contacts_project_id', table_name='contacts')
    op.drop_constraint('fk_contacts_project_id', 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'project_id')
    op.drop_index('idx_messages_project_id', table_name='messages')
    op.drop_constraint('fk_messages_project_id', 'messages', type_='foreignkey')
    op.drop_column('messages', 'project_id')
    op.alter_column('telegram_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('telegram_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telegram_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_telegram_session_name', table_name='telegram_sessions')
    op.create_index('idx_telegram_session_name', 'telegram_sessions', ['session_name'], unique=False)
    op.drop_index('idx_voice_notes_project_id', table_name='voice_notes')
    op.drop_constraint('fk_voice_notes_project_id', 'voice_notes', type_='foreignkey')
    op.drop_column('voice_notes', 'project_id')
    
    op.drop_index('idx_project_telegram_folder_id', table_name='system_projects')
    op.drop_table('system_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_notes', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_voice_notes_project_id', 'voice_notes', 'system_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_voice_notes_project_id', 'voice_notes', ['project_id'], unique=False)
    op.drop_index('idx_telegram_session_name', table_name='telegram_sessions')
    op.create_index('idx_telegram_session_name', 'telegram_sessions', ['session_name'], unique=True)
    op.alter_column('telegram_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('telegram_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('telegram_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('messages', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_messages_project_id', 'messages', 'system_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_messages_project_id', 'messages', ['project_id'], unique=False)
    op.add_column('contacts', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_contacts_project_id', 'contacts', 'system_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_contacts_project_id', 'contacts', ['project_id'], unique=False)
    op.add_column('campaigns', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('campaigns_project_id_fkey', 'campaigns', 'system_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_campaign_project_name', 'campaigns', ['project_id', 'name'])
    op.create_index('idx_campaigns_project_id', 'campaigns', ['project_id'], unique=False)
    op.create_table('system_projects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('telegram_folder_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_projects_pkey')
    )
    op.create_index('idx_project_telegram_folder_id', 'system_projects', ['telegram_folder_id'], unique=False)
    # ### end Alembic commands ###
