"""add_user_profiling_fields

Revision ID: 5f5e4a743410
Revises: b749d28e8331
Create Date: 2026-04-16 13:19:22.902063
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5f5e4a743410'
down_revision: Union[str, None] = 'b749d28e8331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('profile_photo_path', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('is_bot', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contacts', sa.Column('telegram_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'telegram_metadata')
    op.drop_column('contacts', 'last_enriched_at')
    op.drop_column('contacts', 'is_verified')
    op.drop_column('contacts', 'is_bot')
    op.drop_column('contacts', 'profile_photo_path')
    op.drop_column('contacts', 'bio')
    # ### end Alembic commands ###
