"""add_our_channel_ratio

Revision ID: 6fc6fddbcf68
Revises: 838dab9031a1
Create Date: 2026-04-16 15:52:17.023227
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6fc6fddbcf68'
down_revision: Union[str, None] = '838dab9031a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('our_channel_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'our_channel_ratio')
    # ### end Alembic commands ###
