"""Add ad-buyer fields to contact

Revision ID: b2507f0a251d
Revises: 001_initial
Create Date: 2026-04-15 02:35:40.438329
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b2507f0a251d'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('is_ad_buyer', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('ad_buyer_score', sa.Float(), nullable=True))
    op.add_column('contacts', sa.Column('ad_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # op.drop_index('idx_contacts_embedding_hnsw', table_name='contacts', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # op.drop_index('idx_msg_embed_embedding_hnsw', table_name='message_embeddings', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_msg_embed_embedding_hnsw', 'message_embeddings', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # op.create_index('idx_contacts_embedding_hnsw', 'contacts', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('contacts', 'ad_context')
    op.drop_column('contacts', 'ad_buyer_score')
    op.drop_column('contacts', 'is_ad_buyer')
    # ### end Alembic commands ###
